### ISSUE TITLE
Why are the architecture flags not specified everywhere ? 

### ISSUE THREAD

**Issue by AntoineSIMTEK** [IMTEK-Simulation/code-snippets#5]
https://github.com/IMTEK-Simulation/code-snippets/blob/f3da45e2a564373fd02f6c1dfcb69c5e7f1d73ea/singularity/pnetcdf-1.12.2_fftw-3.3.9_pfft-master.def#L64-L93

In the Groupwiki, it is written that we should compile with the flags`-march=sandybridge -mno-avx512f`

I wonder why not all compilations are made using these flags. 

Is there a reason for this @pastewka  ?

**Comment by pastewka** [comment]
Only muSpectre appears to use an optimization level where that matters. I believe FFTW detects the architecture on runtime and switches to the right version.

It would be great if we could specify these compile flags in the base container and then use them in all subsequent containers, but I don't know how to specify environment variable for the compile stage that then surface down the container chain.

**Comment by pastewka** [comment]
(In short, only use these flags if you get a SIGILL - illegal instruction - error)

**Comment by AntoineSIMTEK** [comment]
Ok thank you. I guess I might need this flag when compiling muFFT, depending on which part of the code needs this optimisation.

**Comment by AntoineSIMTEK** [comment]
I can have a look in the singularity doc if I find something like that.

**Comment by pastewka** [comment]
That would be great. For the runtime it's the %environment section, but that is not executed when building the container. (Although one may actually explicity include that, it's a buch of files in `/.singularity` I believe.)
